# Generated by Django 2.1.3 on 2019-04-26 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ziyangroup', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='region',
            field=models.CharField(blank=True, choices=[('dang_wu_gong_kai', '党务公开'), ('huo_dong_lue_ying', '活动掠影'), ('rong_yu_zhan_shi', '荣誉展示'), ('kai_zhan_gong_shi', '开展公示'), ('gui_zhang_zhi_du', '规章制度')], max_length=200),
        ),
    ]
